### ISSUE TITLE
Installed status but timeUpdated doesn't match

### ISSUE THREAD

**Issue by pepe3073** [eI1on/pz-building-menu#16]
GetItemState()=Installed|NeedsUpdate ID=3067798182
LOG  : General     , 1706483137285> 2,032,824,429> Workshop: Installed status but timeUpdated doesn't match!!!

Tried to delete the mop app then re-install. Didn't work. Wondering if there's any issues since the latest update? 
Sorry not a pro but managing to run a modded server. :)

LOG  : General     , 1706483137285> 2,032,824,429> Workshop: GetItemState()=Installed|NeedsUpdate ID=3067798182
LOG  : General     , 1706483137285> 2,032,824,429> Workshop: Installed status but timeUpdated doesn't match!!!
LOG  : General     , 1706483137296> 2,032,824,440> Workshop: item state CheckItemState -> DownloadPending ID=3067798182
LOG  : General     , 1706483137359> 2,032,824,503> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483137362> 2,032,824,506> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483137464> 2,032,824,608> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483137464> 2,032,824,609> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483137581> 2,032,824,725> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483137582> 2,032,824,726> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483137685> 2,032,824,829> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483137685> 2,032,824,829> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483137789> 2,032,824,934> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483137789> 2,032,824,934> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138110> 2,032,825,254> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483138114> 2,032,825,257> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138307> 2,032,825,451> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483138309> 2,032,825,453> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138397> 2,032,825,541> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=3067798182
LOG  : General     , 1706483138398> 2,032,825,542> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138500> 2,032,825,643> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|Downloading|DownloadPending ID=3067798182
LOG  : General     , 1706483138500> 2,032,825,644> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138601> 2,032,825,745> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|Downloading|DownloadPending ID=3067798182
LOG  : General     , 1706483138601> 2,032,825,746> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138703> 2,032,825,848> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|Downloading|DownloadPending ID=3067798182
LOG  : General     , 1706483138704> 2,032,825,848> Workshop: download 0/1509760 ID=3067798182
LOG  : General     , 1706483138738> 2,032,825,883> Workshop: onItemNotDownloaded itemID=3067798182 result=2
LOG  : General     , 1706483138739> 2,032,825,883> Workshop: item state DownloadPending -> Fail ID=3067798182
src\tier0\threadtools.cpp (3690) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier0\threadtools.cpp (3690) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier0\threadtools.cpp (3690) : Assertion Failed: Illegal termination of worker thread 'Thread(0x00007FFB84827DA0/0x000'
src\tier0\threadtools.cpp (3690) : Assertion Failed: Illegal termination of worker thread 'Thread(0x00007FFB84827DA0/0x000'

**Comment by eI1on** [comment]
That's not necessarily an issue from the mod, it could be a symptom of server crashes in the past, network issues, permissions, problems with the Steam Workshop servers., or some other underlying problem. You can try to delete all files and folders inside Project Zomboid Dedicated Server\steamapps\workshop, this will force the server to redownload all mods.

**Comment by pepe3073** [comment]
Thanks so much for your help! I will try this.

Sent from Proton Mail mobile

-------- Original Message --------
