### ISSUE TITLE
Half glass roof panels

### ISSUE THREAD

**Issue by reinaldogpn** [eI1on/pz-building-menu#18]
Hi there!

Is these "half roof panels" available in your mod? I can't find it anywhere.
![half](https://github.com/eI1on/pz-building-menu/assets/106502559/f47c03fd-ac61-4ae1-8247-22be01a72176)

**Comment by eI1on** [comment]
Added with this commit: 3f7a8afea6eba1035624cfb7b7b0f306c4ab0660
