### ISSUE TITLE
Able to stack containers/furniture

### ISSUE THREAD

**Issue by user2345679** [eI1on/pz-building-menu#19]
You are able to stack unique containers on top of each other as long as they are built from the build menu. Not a problem in single player but can be an issue in multiplayer.
Example shown in video 

https://github.com/eI1on/pz-building-menu/assets/160158836/1492ac85-d57b-4ab4-800d-b68d135159f7

**Comment by eI1on** [comment]
Solved with this commit: [](b51e6eae4dcc8f033c5a7efc12e442f9b8807133)

**Comment by eI1on** [comment]
Solved with this commit: [b51e6eae4dcc8f033c5a7efc12e442f9b8807133](url)

**Comment by eI1on** [comment]
Solved with this commit: [https://github.com/eI1on/pz-building-menu/commit/b51e6eae4dcc8f033c5a7efc12e442f9b8807133](b51e6ea)

**Comment by eI1on** [comment]
Solved with this commit [b51e6ea](https://github.com/eI1on/pz-building-menu/commit/b51e6eae4dcc8f033c5a7efc12e442f9b8807133)
