### ISSUE TITLE
[Question] Survival>Metal Drum> What is the low drum's purpose?

### ISSUE THREAD

**Issue by user2345679** [eI1on/pz-building-menu#21]
Hello, I am wondering what the lower drum is for in this list? I imagine it is a type of rain collector but I was not sure why it's size is so big and why it's placement is unlike other items in the menus.
I notice that when built on ground level that grass clips over it and I can walk on it (there is an invisible square above it that cant be clipped into though), is it some type of underground barrel?
![image](https://github.com/eI1on/pz-building-menu/assets/160158836/3e12793c-f1db-4135-9ce6-796441abd370)
![image](https://github.com/eI1on/pz-building-menu/assets/160158836/f8b66271-d30f-4ab5-aec5-e6de98ab454c)

**Comment by user2345679** [comment]
update: I believe I have found the issue. In my original post I had the Options > Display > Textures > 'Double-sized Textures' turned OFF. After turning it ON, the barrels are now properly sized, have proper hit box and no longer appear 'under the terrain'.
The same goes for the military crate (which used to be huge and buggy when building with the double-sized texture option turned off.
![image](https://github.com/eI1on/pz-building-menu/assets/160158836/c9ed3204-fd6c-4ffc-9ddc-af85945c0e28)

**Comment by eI1on** [comment]
This problem you encountered with the tiles appearing incorrectly is a known compatibility issue with Project Zomboid when using modded tilepacks. Seeing that you found the solution I will close this issue.
