### ISSUE TITLE
All lighting has huge radius when built, when picked up+placed the radius is reduced

### ISSUE THREAD

**Issue by user2345679** [eI1on/pz-building-menu#22]
All lighting objects behave this way
1) build a light object (it will have a huge radius of lighted tiles)
2) pick up the light object
3) place the light object
4) the light will now have a reduced light radius

https://github.com/eI1on/pz-building-menu/assets/160158836/c52d61e9-c5a0-4e52-9dbe-1645d1ec567b

Another lighting bug is the 'indoor' light switch also builds with a large light radius. The 'indoor' light switch can also be built outside on any empty tile (doesn't require being built on a wall etc)

**Comment by eI1on** [comment]
I'll adjust the light radius on items you can build from BM to the radius they have in the vanilla game.
