### ISSUE TITLE
[Request] More add-on mods for tile packs

### ISSUE THREAD

**Issue by vico93** [eI1on/pz-building-menu#23]
I absolutely adore the available add-on packs made for Building Menu.

But after discovering other amazing tile packs while downloading a couple of mods i would ask if you could do add-on mods correspondent for these ones too.

- [Simon MDs Destroyed Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=2862154374)
- [Fear's Funky Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=2901328637)
- [Skizot's Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=2740919036)
- [ivery's Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=2898138850)
- [Oujinjin's Tile Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2844829195)
- [ExtraNoise's Newburbs Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=2774834715)
- [ExtraNoise's Flag Tiles](https://steamcommunity.com/sharedfiles/filedetails/?id=2784607980)

Thank you so much for this mod!

**Comment by eI1on** [comment]
Thanks for the suggestions, but first I want to make sure the main mod is as stable and bug-free as possible. After that, I'll consider adding new addons. BM is a framework, so anyone is free to create addons too.

**Comment by Spudli** [comment]
Is there a guide on how to create the add-ons?

**Comment by eI1on** [comment]
[Development Guide](https://github.com/eI1on/pz-building-menu/blob/main/DEVELOPMENT.md), you can also check the code in the addons.

**Comment by DeZeeuw2** [comment]
Garage Doors, even vanilla ones, are notoriously prone to desync, even in single player games.  I'm glad you have the sandbox option to disable them in the base mod, just hoping you could also add that option to ExtraNoise's addon, Melo's addon, Pert's addon, and Simon's addon.  For a larger player count MP server, it would save a lot of extra work for the staff if players can't even build garage doors in the first place.  Thanks

**Comment by eI1on** [comment]
Disabling the sandbox option for garage doors affect the addons too, as they only include garage doors if the sandbox option in the main mod is enabled. But this problem with desynchronization of garages has been solved, it is no longer inherited from More Builds.

**Comment by eI1on** [comment]
Oh, and an update to this request:
[Building Menu - Oujinjin's Tiles Addon](https://steamcommunity.com/sharedfiles/filedetails/?id=3246567767)
[Building Menu - ExtraNoise's Newburbs Tiles Addon](https://steamcommunity.com/sharedfiles/filedetails/?id=3225710182)
[Building Menu - ExtraNoise's Flag Tiles Addon](https://steamcommunity.com/sharedfiles/filedetails/?id=3238881965)

**Comment by vico93** [comment]
Thank you so much!

**Comment by fairda1** [comment]
Hey can you add Pink Brick exterior arch's is missing from the build menu options its missing i was hoping you could add it

**Comment by eI1on** [comment]
Added the Pink Brick exterior arch with this [#8cf69aa](https://github.com/eI1on/pz-building-menu/commit/8cf69aa17fc16579dddd2ea8c0b5774efb2ee6bd) commit.

**Comment by eI1on** [comment]
I will also close this thread because I no longer plan to make addons, and after the B42 release this mod will become redundant.
