### ISSUE TITLE
[bugs] Recently completed issues still existing

### ISSUE THREAD

**Issue by user2345679** [eI1on/pz-building-menu#28]
((I am new to this game so please excuse me if for some reason I don't have the proper version, I re-downloaded the current workshop version and verified files to double check))

1) 'Climb Over' bug still occurs on the razor wire fence object as mentioned in this previous issue: 
https://github.com/eI1on/pz-building-menu/issues/27

2) This bug was mentioned on steam discussions and was fixed in one of the patch notes but still exists: All General > Floor > 'Tile' types of tiles that require carpentry+wood planks+nails still disassemble using metalworking and return metal sheets + small metal sheets

----
P.S. I am new to github, if I encounter this in the future and should just comment on the old closed thread instead of making a new one, please let me know. Thanks again for your time, love the mod.

**Comment by eI1on** [comment]
1. I forgot to mention but it is fixed only for newly built fences.
2. It should be fixed now. For some reason it didn't save the Wood material when I modified it.

It's okay, you can open another issue.
