### ISSUE TITLE
Tiles gone missing. Built variants are deleted from the world.

### ISSUE THREAD

**Issue by Sakabashira** [eI1on/pz-building-menu#33]
Recently I downloaded a whole host of new mods, mostly being map mods. Prior to activating them all, the mod worked with no known issues other than some tiles cannot be rotated after placement, or can only be rotated after placement. I've tried deactivating all the mods and starting a new save, but the problem persists. Trying to trouble shoot by progressively disabling mods one at a time to figure out if it's simply an incompatibility doesn't appear to work. Only thing I've noticed is that after trying to troubleshoot, starting over a dozen new saves, the mod suddenly starts working again, but I cannot find any correlation between the mods disabled and this mod working again. After re-enabling all the mods to be sure, this mod continues to function fine until closing the game to desktop. I did make a backup just prior to adding the map mods, so I have a version of my save that wasn't experiencing the bug. I understand the error is likely my hubris in trying to play the game with so many mods enabled, but I was hoping to get a lot of these mods to play nice together and overlap the maps. I noticed the Throttlekitty pack also suffers the issue, but disabling that mod didn't appear to fix anything. And yes, I've tried redownloading all associated mods, multiple times. 

Here is a copy of the console text from a fresh save with all mods enabled. Appreciated.

![image_2024-05-19_172338781](https://github.com/eI1on/pz-building-menu/assets/22876001/bc3f7739-895a-4c06-8e9f-de4f38d7112d)
![image_2024-05-19_172404439](https://github.com/eI1on/pz-building-menu/assets/22876001/3432a7a7-7766-4fb1-add7-bc6468b3a28d)
![image_2024-05-19_172541589](https://github.com/eI1on/pz-building-menu/assets/22876001/eec92148-f70d-456e-a96c-bccf76a97ae6)

[console.txt](https://github.com/eI1on/pz-building-menu/files/15371347/console.txt)

**Comment by eI1on** [comment]
Can you export the mod list? The addons are loaded after tile packs, so they should appear. I see you're using Mod Manager, which allows you to export/import mods with this addon https://steamcommunity.com/sharedfiles/filedetails/?id=3204323366

**Comment by Sakabashira** [comment]
[MyList.txt](https://github.com/eI1on/pz-building-menu/files/15373257/MyList.txt)

**Comment by eI1on** [comment]
These maps [Klin - Russian City](https://steamcommunity.com/sharedfiles/filedetails/?id=2790749470) [Wildberries](https://steamcommunity.com/sharedfiles/filedetails/?id=2773732963) may conflict with Daddy Dirkie dirks tiles because they contain copies of this tilepack in them, which they shouldn't. You also probably have other map mods that are incompatible with each other or have the same problems. I suggest you check them all.

Also you have 4-6 year old mods, I recommend not using those because the game has been updated since, and these can cause problems.

**Comment by Sakabashira** [comment]
Some map mods I was hoping to have combine with others, even though the roads don't match up I'd figure I'd just pave some down to it since the distances aren't that much, but yes, I see. Didn't think they'd have the tile sets combined into the mod. Wildberries and Chestown for instance having overlapping cells, because I like the upper half of Chestown and lower half of Wildberries. Not mod savvy enough to physically combine their cells into one mod for my singleplayer playstyle. Same with Big Bear and Fort Benning, being out in the wilderness and replacing little in Big Bear besides trees and car spawns and some huts. But yes, I understand.

I'll check again on what can be removed. Do you happen to know of any other map mods that coincidentally contain tile packs inside off the top to avoid? Or could assist in telling me which ones are like that that I have? I was aiming to populate my map with as many maps together that I could.

**Comment by Sakabashira** [comment]
Would simply deleting the tile packs from the mods that have them built be enough? And anything related to the specific cells I'd like to keep in others?

**Comment by Sakabashira** [comment]
Decided to give that a try, deleting the tile pack in Klin, and deleting/renaming map/cell files in other map mods appears to have fixed my problems. Appreciated for the assistance. Honestly didn't think it'd work that easily, but it did.
