### ISSUE TITLE
Building Menu [B41.78] mod issue

### ISSUE THREAD

**Issue by GBharatRaj** [eI1on/pz-building-menu#39]
This mod is causing issue with "Vehicle Repair Overhaul mod" with propane torches salvaging and dismantling mechanics. It is showing "4/10 propane torch" needed even though I have 20 propane torches in my inventory(same issue with dismantling). Can you please fix this issue or is there already a solution that I am missing here? please help!!

**Comment by eI1on** [comment]
You likely set blow torches to 4 uses in the sandbox options, but Vehicle Repair Overhaul only checks for a single blow torch, not the total uses across multiple. To fix this, go to Sandbox Options > Building Menu Recipes > Blow Torch Uses, click the dropdown, and select 10 uses or more.

**Comment by eI1on** [comment]
![image](https://github.com/user-attachments/assets/f6a0859b-764e-4d41-a2b2-205d30115904)
To change sandbox options in an on-going SP game use https://steamcommunity.com/sharedfiles/filedetails/?id=2894296454

**Comment by GBharatRaj** [comment]
How did I miss that, it is I who changed it to 4 and forgot about that setting🤦‍♂️, thank you for reminding me my ignorance. Thank you so much 🙏🏻.
