### ISSUE TITLE
missing names impossible translate

### ISSUE THREAD

**Issue by BrenoS93** [eI1on/pz-building-menu#44]
play video https://drive.google.com/file/d/1Sn6ndIPh7xThMT8x1pF_jC38hVrXawk-/view?usp=sharing

Decoraçõs > Pôster

Banner

Decorações > Placas

Sinal Spiffo

Tapete

Victorian 1 Rug
Victorian 2 Rug
Victorian 3 Rug
Victorian 4 Rug

Móveis > Poltrona

Victorian C1 Couch
Victorian 2 Chair
Victorian C2 Couch
Victorian 1 Chair
Victorian C3 Couch
Victorian 3 Chair
Victorian C4 Couch
Victorian 4 Chair
Victorian C5 Couch
Victorian 5 Chair

Móveis > Cama Simples

furniture_bedding_01_89
furniture_bedding_01_93

**Comment by eI1on** [comment]
I’ve added the necessary translation keys for the buildables you mentioned in [9001e4a](https://github.com/eI1on/pz-building-menu/commit/9001e4a5ef328ef90385dc6eaebf7aa0cee602d6). 

You can find them in the updated file now. Also, keep in mind that the base game `Moveables_EN.txt` (located in `ProjectZomboid\media\lua\shared\Translate\EN\Moveables_EN.txt`) contains more moveable objects names that are part of my mod and probably that are not translated. 

The translation keys are generated dynamically from the `GroupName` and `CustomName` sprite properties of objects, as shown in this image 
![Screenshot 2024-09-22 205405](https://github.com/user-attachments/assets/cecfad1f-b71e-42b8-ba1b-90fc23fcae87)

**Comment by BrenoS93** [comment]
thank you very much, now i can finish all for complete
other thing that i want you see
https://drive.google.com/file/d/1ASjbn1K0zHJyqfnOfn15W0FngTveK4xL/view?usp=sharing
i don't know if the game bug or happen only with me here
all mods that is using this are duplicating this category on crafting menu
