### ISSUE TITLE
Perpetual Error Throwing While Standing On BM Option's Required Resources

### ISSUE THREAD

**Issue by jaxx050** [eI1on/pz-building-menu#45]
https://pastebin.com/scGP6qv3

If you're attempting to select a Building Menu option's buildable in the menu, and that option's required resources are on the ground underneath you, the game will just throw an error every single tick and not actually allow you to select that option to build until you either pick up the required resources or move away from them.

**Comment by eI1on** [comment]
This bug has been fixed in #40 and will be implemented in the next update
